Fix compiler warning that occurs with link-time optimization
With LTO enable, the build fails with:

 [100%] Linking C executable hatari
 .../src/cpu/savestate.h:281:14: error: type of 'savestate_fname' does not
  match original declaration [-Werror=lto-type-mismatch]
   281 | extern TCHAR savestate_fname[MAX_DPATH];
       |              ^
 .../src/cpu/custom.c:40:8: note:
  'savestate_fname' was previously declared here
    40 | TCHAR *savestate_fname;
       |        ^
 lto1: all warnings being treated as errors

Declare the array according to the definition in the header file to fix it.