Fix declaration of the _xlate functions in case REGPARAM3 is set
Otherwise there are compilation errors with VisualStudio:

 src\cpu\memory.c(60): error C2165: 'left-side modifier': cannot modify
 pointers to data